name: Hewalex2Mqtt
version: "1.4.0"
slug: hewalex2mqtt
description: Hewalex PCWU warmtepomp en ZPS zonneboiler naar MQTT
arch:
  - aarch64
  - amd64
init: false
startup: application
boot: auto
options:
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_user: hewalexwp
  mqtt_pass: ""
  pcwu_host: 192.168.178.228
  pcwu_port: 4198
  pcwu_dev_id: 3
  zps_enabled: true
  zps_host: 192.168.178.245
  zps_port: 8899
  zps_dev_id: 2
schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str
  mqtt_pass: password
  pcwu_host: str
  pcwu_port: port
  pcwu_dev_id: int
  zps_enabled: bool
  zps_host: str
  zps_port: port
  zps_dev_id: int
